// <auto-generated />
using System;
using AlphaManagement.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlphaManagement.DAL.Migrations
{
    [DbContext(typeof(AlphaDbContext))]
    [Migration("20210523140419_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlphaManagement.DAL.Entity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<string>("bpNo")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(120);

                    b.Property<int?>("isActive");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Auth.AlphaModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<string>("isTeam");

                    b.Property<string>("moduleName");

                    b.Property<string>("moduleNameBN");

                    b.Property<int?>("shortOrder");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("AlphaModules");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Auth.ModuleAccessPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("alphaModuleId");

                    b.Property<string>("applicationRoleId");

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("alphaModuleId");

                    b.HasIndex("applicationRoleId");

                    b.ToTable("ModuleAccessPages");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Auth.Navbar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("action")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("activeLi")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("area")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("controller")
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("displayOrder");

                    b.Property<string>("imageClass")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("isDelete");

                    b.Property<int?>("isParent");

                    b.Property<int?>("moduleId");

                    b.Property<string>("nameOption")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("nameOptionBangla")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("parentID");

                    b.Property<bool>("status");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("moduleId");

                    b.ToTable("Navbars");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Auth.UserAccessPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("applicationRoleId");

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isAccess");

                    b.Property<int?>("isDelete");

                    b.Property<int?>("navbarId");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("applicationRoleId");

                    b.HasIndex("navbarId");

                    b.ToTable("UserAccessPages");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.EmployeeInfo.EmployeeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId");

                    b.Property<DateTime?>("LPRDate");

                    b.Property<DateTime?>("PRLEndDate");

                    b.Property<DateTime?>("PRLStartDate");

                    b.Property<int?>("activityStatus");

                    b.Property<string>("batch");

                    b.Property<string>("birthIdentificationNo")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("birthPlace")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("bloodGroup")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("branchId");

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("dateOfBirth");

                    b.Property<DateTime?>("dateOfPermanent");

                    b.Property<DateTime?>("dateofregularity");

                    b.Property<int?>("departmentId");

                    b.Property<string>("designation")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("designationCheck");

                    b.Property<int?>("designationsId");

                    b.Property<string>("disability")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("emailAddress")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("emailAddressPersonal")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("employeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("employeeTypeId");

                    b.Property<string>("fatherNameBangla")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fatherNameEnglish")
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("freedomFighter");

                    b.Property<string>("freedomFighterNo")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gender")
                        .HasMaxLength(10);

                    b.Property<string>("govtID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gpfAcNo")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gpfNomineeName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("homeDistrict")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("isApproved");

                    b.Property<int?>("isDelete");

                    b.Property<DateTime?>("joiningDateGovtService");

                    b.Property<DateTime?>("joiningDatePresentWorkstation");

                    b.Property<string>("joiningDesignation")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("maritalStatus")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("mobileNumberOffice")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("mobileNumberPersonal")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("motherNameBangla")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("motherNameEnglish")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("nameBangla")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("nameEnglish")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("nationalID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nationality")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("natureOfRequitment")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("pabx")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("post");

                    b.Property<int?>("rankId");

                    b.Property<int?>("religionId");

                    b.Property<int?>("sectionId");

                    b.Property<string>("seniorityNumber")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("skypeId")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("specialSkill")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("telephoneOffice")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telephoneResidence")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("branchId");

                    b.HasIndex("departmentId");

                    b.HasIndex("designationsId");

                    b.HasIndex("employeeTypeId");

                    b.HasIndex("rankId");

                    b.HasIndex("religionId");

                    b.HasIndex("sectionId");

                    b.ToTable("EmployeeInfos");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.ActivityStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<string>("shortName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("statusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("statusNameBn")
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("ActivityStatuses");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.CourseTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<string>("nameBN")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("nameEN")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("CourseTitles");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.Degree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<string>("degreeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("degreeNameBn")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("degreeShortName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("isDelete");

                    b.Property<int>("levelofeducationId");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("levelofeducationId");

                    b.ToTable("Degrees");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<string>("deptCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("deptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("deptNameBn")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("isDelete");

                    b.Property<string>("shortName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("startDate");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<string>("designationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("designationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("designationNameBN")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("isDelete");

                    b.Property<string>("shortName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("shortOrder");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.EmployeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<string>("empType")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("empTypeBn")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("isDelete");

                    b.Property<string>("shortName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("EmployeeTypes");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<string>("languageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("languageNameBn")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("languageShortName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("shortOrder");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.LevelofEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<string>("levelofeducationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("levelofeducationNameBn")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("shortOrder");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("LevelofEducations");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<string>("rankCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("rankName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("rankNameBN")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("shortName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("shortOrder");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.RelDegreeSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int>("degreeId");

                    b.Property<int?>("isDelete");

                    b.Property<int>("subjectId");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("degreeId");

                    b.HasIndex("subjectId");

                    b.ToTable("RelDegreeSubjects");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.Relation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<string>("relationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("relationNameBn")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("relationShortName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Relations");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.Religion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("nameBn")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("shortName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Religions");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<decimal>("resultMaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("resultName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("resultNameBn")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("resultShortName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameBN")
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<string>("shortName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("shortOrder");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.SpecialBranchUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("branchCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("branchUnitName")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("branchUnitNameBN")
                        .HasColumnType("nvarchar(350)");

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<int?>("isdefault");

                    b.Property<int?>("shortOrder");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("SpecialBranchUnits");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<int?>("shortOrder");

                    b.Property<string>("subjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("subjectNameBn")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("subjectShortName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.TrainingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<int?>("shortOrder");

                    b.Property<string>("trainingCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("trainingCategoryNameBn")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("trainingCategoryShortName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("TrainingCategories");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.TrainingInstitute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<int?>("shortOrder");

                    b.Property<string>("trainingInstituteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("trainingInstituteNameBn")
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("trainingInstituteShortName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("TrainingInstitutes");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.Year", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<string>("createdBy")
                        .HasMaxLength(250);

                    b.Property<int?>("isDelete");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("updatedAt");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(250);

                    b.Property<string>("year")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Years");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Auth.ModuleAccessPage", b =>
                {
                    b.HasOne("AlphaManagement.DAL.Entity.Auth.AlphaModule", "alphaModule")
                        .WithMany()
                        .HasForeignKey("alphaModuleId");

                    b.HasOne("AlphaManagement.DAL.Entity.ApplicationRole", "applicationRole")
                        .WithMany()
                        .HasForeignKey("applicationRoleId");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Auth.Navbar", b =>
                {
                    b.HasOne("AlphaManagement.DAL.Entity.Auth.AlphaModule", "module")
                        .WithMany()
                        .HasForeignKey("moduleId");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Auth.UserAccessPage", b =>
                {
                    b.HasOne("AlphaManagement.DAL.Entity.ApplicationRole", "applicationRole")
                        .WithMany()
                        .HasForeignKey("applicationRoleId");

                    b.HasOne("AlphaManagement.DAL.Entity.Auth.Navbar", "navbar")
                        .WithMany()
                        .HasForeignKey("navbarId");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.EmployeeInfo.EmployeeInfo", b =>
                {
                    b.HasOne("AlphaManagement.DAL.Entity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("AlphaManagement.DAL.Entity.Master.SpecialBranchUnit", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");

                    b.HasOne("AlphaManagement.DAL.Entity.Master.Department", "department")
                        .WithMany()
                        .HasForeignKey("departmentId");

                    b.HasOne("AlphaManagement.DAL.Entity.Master.Designation", "designations")
                        .WithMany()
                        .HasForeignKey("designationsId");

                    b.HasOne("AlphaManagement.DAL.Entity.Master.EmployeeType", "employeeType")
                        .WithMany()
                        .HasForeignKey("employeeTypeId");

                    b.HasOne("AlphaManagement.DAL.Entity.Master.Rank", "rank")
                        .WithMany()
                        .HasForeignKey("rankId");

                    b.HasOne("AlphaManagement.DAL.Entity.Master.Religion", "religion")
                        .WithMany()
                        .HasForeignKey("religionId");

                    b.HasOne("AlphaManagement.DAL.Entity.Master.Section", "section")
                        .WithMany()
                        .HasForeignKey("sectionId");
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.Degree", b =>
                {
                    b.HasOne("AlphaManagement.DAL.Entity.Master.LevelofEducation", "levelofeducation")
                        .WithMany()
                        .HasForeignKey("levelofeducationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AlphaManagement.DAL.Entity.Master.RelDegreeSubject", b =>
                {
                    b.HasOne("AlphaManagement.DAL.Entity.Master.Degree", "degree")
                        .WithMany()
                        .HasForeignKey("degreeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlphaManagement.DAL.Entity.Master.Subject", "subject")
                        .WithMany()
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("AlphaManagement.DAL.Entity.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AlphaManagement.DAL.Entity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AlphaManagement.DAL.Entity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("AlphaManagement.DAL.Entity.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlphaManagement.DAL.Entity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AlphaManagement.DAL.Entity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
